/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import coil.prototipo.logica.Aula;
import coil.prototipo.logica.Docente;
import database.dbConnections;
import java.util.ArrayList;
import Controller.Controlador;
/**
 * Panel que muestra información detallada de un Aula para el docente.
 */
public class AulaInfoPanelDocente extends javax.swing.JPanel {

    private Controlador controlador;
    private Aula currentAula;

    public AulaInfoPanelDocente(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VolverBoton = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDocente = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        EditarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("Informacion Aula");

        VolverBoton.setText("Volver");
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });

        jLabelNombre.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelDocente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelDocente.setText("Descripcion");

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelCodigo.setText("Codigo");

        jLabelDesc.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelDesc.setText("Docente");

        EditarBoton.setText("Editar");
        EditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jLabelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(VolverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(EditarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        controlador.volverPanelAnterior();
    }//GEN-LAST:event_VolverBotonActionPerformed

    private void EditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBotonActionPerformed
        if (currentAula == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay aula seleccionada.");
            return;
        }

        javax.swing.JTextField nombreField = new javax.swing.JTextField(currentAula.getNombre() != null ? currentAula.getNombre() : "");
        javax.swing.JTextArea descArea = new javax.swing.JTextArea(currentAula.getDescripcion() != null ? currentAula.getDescripcion() : "", 6, 30);
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(descArea);
        Object[] inputs = {"Nombre:", nombreField, "Descripción:", scroll};

        int res = javax.swing.JOptionPane.showConfirmDialog(this, inputs, "Editar Aula", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (res == javax.swing.JOptionPane.OK_OPTION) {
            String nuevoNombre = nombreField.getText().trim();
            String nuevaDesc = descArea.getText().trim();
            if (nuevoNombre.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
                return;
            }
            boolean ok = controlador.editarAula(String.valueOf(currentAula.getId_aula()), nuevoNombre, nuevaDesc);
            if (ok) {
                currentAula.setNombre(nuevoNombre);
                currentAula.setDescripcion(nuevaDesc);
                setAula(currentAula);
                javax.swing.JOptionPane.showMessageDialog(this, "Aula actualizada correctamente.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar el aula. Revisa logs.");
            }
        }
    }//GEN-LAST:event_EditarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        if (currentAula == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay aula seleccionada.");
            return;
        }
        int confirmado = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Confirma eliminar el aula \"" + (currentAula.getNombre() != null ? currentAula.getNombre() : currentAula.getId_aula()) + "\" ?",
                "Eliminar Aula", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirmado == javax.swing.JOptionPane.YES_OPTION) {
            boolean ok = controlador.eliminarAula(String.valueOf(currentAula.getId_aula()));
            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Aula eliminada.");
                setAula(null);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el aula. Revisa logs.");
            }
        }
    }//GEN-LAST:event_EliminarBotonActionPerformed

    
    public void setAula(Aula aula) {
        this.currentAula = aula;
        if (aula == null) {
            jLabelNombre.setText("Nombre: -");
            jLabelCodigo.setText("Código inscripción: -");
            jLabelDocente.setText("Docente: -");
            jLabelDesc.setText("Descripción: -");
            return;
        }
        jLabelNombre.setText("Nombre: " + (aula.getNombre() != null ? aula.getNombre() : "-"));
        jLabelCodigo.setText("Código inscripción: " + (aula.getCodigo_inscripcion() != null ? aula.getCodigo_inscripcion() : "-"));
        jLabelDesc.setText("Descripción: " + (aula.getDescripcion() != null ? aula.getDescripcion() : "-"));
        if (aula.getDocente() != null) {
            Docente d = aula.getDocente();
            jLabelDocente.setText("Docente: " + (d.getNombre_completo() != null ? d.getNombre_completo() : d.getCodigoDocente()));
        } else {
            jLabelDocente.setText("Docente: -");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarBoton;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelDocente;
    private javax.swing.JLabel jLabelNombre;
    // End of variables declaration//GEN-END:variables
}
