/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Controller.Controlador;
import Personalizacion.BordeRedondeado;



public class InicioPanel extends javax.swing.JPanel {
    
    Controlador controlador;
    /**
     * Creates new form InicioPanal
     */
    public InicioPanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RegistrarseBoton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/login boton.png"))); // NOI18N
        LoginBoton.setBorderPainted(false);
        LoginBoton.setContentAreaFilled(false);
        LoginBoton.setFocusPainted(false);
        LoginBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/login boton hover.png"))); // NOI18N
        LoginBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBotonActionPerformed(evt);
            }
        });
        add(LoginBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 220, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        RegistrarseBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/registrar boton.png"))); // NOI18N
        RegistrarseBoton.setBorderPainted(false);
        RegistrarseBoton.setContentAreaFilled(false);
        RegistrarseBoton.setFocusPainted(false);
        RegistrarseBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/registrar boton hover.png"))); // NOI18N
        RegistrarseBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseBotonActionPerformed(evt);
            }
        });
        add(RegistrarseBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 220, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarseBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseBotonActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVentana("registrar");
    }//GEN-LAST:event_RegistrarseBotonActionPerformed

    private void LoginBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBotonActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVentana("login");

    }//GEN-LAST:event_LoginBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBoton;
    private javax.swing.JButton RegistrarseBoton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
