/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Controller.Controlador;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author Luis
 */
public class InicioSesionPanel extends javax.swing.JPanel {

    private Controlador controlador;
    private int tipo;
    /**
     * Creates new form InicioSesionPanel
     */
    public InicioSesionPanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        tipo = 1;
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                usernameField.setText("");
                passwordField.setText("");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SiguienteBoton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonTipo = new javax.swing.JButton();
        LogoutBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SiguienteBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Boton Aceptar (azul).png"))); // NOI18N
        SiguienteBoton.setBorderPainted(false);
        SiguienteBoton.setContentAreaFilled(false);
        SiguienteBoton.setFocusPainted(false);
        SiguienteBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Boton Aceptar (azul)_hover.png"))); // NOI18N
        SiguienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteBotonActionPerformed(evt);
            }
        });
        add(SiguienteBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 140, 120));

        usernameField.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 260, 40));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 260, 40));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel3.setText("Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 150, 40));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre de Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 240, 50));

        BotonTipo.setBackground(new java.awt.Color(0, 102, 255));
        BotonTipo.setFont(BotonTipo.getFont().deriveFont(BotonTipo.getFont().getSize()+6f));
        BotonTipo.setForeground(new java.awt.Color(51, 153, 255));
        BotonTipo.setText("LOGIN DOCENTE");
        BotonTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTipoActionPerformed(evt);
            }
        });
        add(BotonTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 230, 50));

        LogoutBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        LogoutBoton.setBorderPainted(false);
        LogoutBoton.setContentAreaFilled(false);
        LogoutBoton.setFocusPainted(false);
        LogoutBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        LogoutBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBotonActionPerformed(evt);
            }
        });
        add(LogoutBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/3.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteBotonActionPerformed
        // TODO add your handling code here:
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());
        
        // ¡La única línea de lógica!
        controlador.Login(username, password, tipo);
    }//GEN-LAST:event_SiguienteBotonActionPerformed

    private void BotonTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTipoActionPerformed
        // TODO add your handling code here:
                if (tipo == 2) {
            tipo = 1;
            this.BotonTipo.setText("LOGIN DOCENTE");
        }
        else {
            tipo = 2;
            this.BotonTipo.setText("LOGIN ESTUDIANTE");
        }
    }//GEN-LAST:event_BotonTipoActionPerformed

    private void LogoutBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBotonActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVentana("inicio");
    }//GEN-LAST:event_LogoutBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonTipo;
    private javax.swing.JButton LogoutBoton;
    private javax.swing.JButton SiguienteBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
