/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Estudiante;

import GUI.Docente.*;
import Controller.Controlador;
import coil.prototipo.logica.Actividad;
import java.awt.Component;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author luisr
 */
public class ActividadesPanelEstudiante extends javax.swing.JPanel {
    private Controlador controlador;
    /**
     * Creates new form CrearActividadPanel
     * @param controlador
     */
    public ActividadesPanelEstudiante(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        this.controlador.setListaActividades();
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                
                controlador.llenarTablaActividades(TablaActividades);
            }
        });
        
        VerActividadBoton.addActionListener(evt -> {
            int pos = TablaActividades.getSelectedRow();
            if (pos == -1) {
                JOptionPane.showMessageDialog(this, "Selecciona una actividad primero.", "Sin selección", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String[] act = {TablaActividades.getValueAt(pos, 0).toString(),
            TablaActividades.getValueAt(pos, 1).toString(),
            TablaActividades.getValueAt(pos, 2).toString()};
            controlador.setActividadEnVista(new Actividad("1", act[0], act[1], LocalDateTime.parse(act[2]), 20, "Matemática"));
            controlador.cambiarVentana("ActPanInfoEst");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelarBoton = new javax.swing.JButton();
        VerActividadBoton = new javax.swing.JButton();
        ContenedorTabPorAula = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaActividades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        CancelarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CancelarBoton.setBorderPainted(false);
        CancelarBoton.setContentAreaFilled(false);
        CancelarBoton.setFocusPainted(false);
        CancelarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });
        add(CancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 100, 70));

        VerActividadBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/ver actividad boton.png"))); // NOI18N
        VerActividadBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        VerActividadBoton.setBorderPainted(false);
        VerActividadBoton.setContentAreaFilled(false);
        VerActividadBoton.setFocusPainted(false);
        VerActividadBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/boton ver actividad hover.png"))); // NOI18N
        VerActividadBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActividadBotonActionPerformed(evt);
            }
        });
        add(VerActividadBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 280, 110));

        TablaActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción", "Fecha Pautada"
            }
        ));
        jScrollPane1.setViewportView(TablaActividades);

        ContenedorTabPorAula.addTab("Actividades Por Hacer", jScrollPane1);

        add(ContenedorTabPorAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 470, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/16.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        controlador.volverPanelDashboard();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void VerActividadBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerActividadBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerActividadBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JTabbedPane ContenedorTabPorAula;
    private javax.swing.JTable TablaActividades;
    private javax.swing.JButton VerActividadBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
