/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Estudiante;
import Controller.Controlador;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
/**
 *
 * @author luisr
 */
public class DashboardEstudiante extends javax.swing.JPanel {

    private Controlador controlador;
    
    
    public DashboardEstudiante(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                // This code will execute when the JPanel becomes visible
                BienvenidaTexto.setText("¡Bienvenido, " + controlador.getEstudianteLogueado().getNombre_completo() + "!");

                // Perform actions here that should happen when the panel is displayed
            }
        });
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AulasBoton = new javax.swing.JButton();
        ActividadesBoton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LogoutBoton = new javax.swing.JButton();
        BienvenidaTexto = new javax.swing.JLabel();
        CalificacionesBoton = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        AulasBoton.setBackground(new java.awt.Color(204, 204, 204));
        AulasBoton.setForeground(new java.awt.Color(0, 0, 0));
        AulasBoton.setText("Aulas");
        AulasBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AulasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AulasBotonActionPerformed(evt);
            }
        });

        ActividadesBoton.setBackground(new java.awt.Color(204, 204, 204));
        ActividadesBoton.setForeground(new java.awt.Color(0, 0, 0));
        ActividadesBoton.setText("Actividades");
        ActividadesBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ActividadesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActividadesBotonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        LogoutBoton.setBackground(new java.awt.Color(204, 204, 204));
        LogoutBoton.setFont(LogoutBoton.getFont());
        LogoutBoton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBoton.setText("Log out");
        LogoutBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LogoutBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBotonActionPerformed(evt);
            }
        });

        BienvenidaTexto.setBackground(new java.awt.Color(255, 255, 255));
        BienvenidaTexto.setFont(BienvenidaTexto.getFont().deriveFont(BienvenidaTexto.getFont().getSize()+7f));
        BienvenidaTexto.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidaTexto.setText("¡Bienvenido, Estudiante!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BienvenidaTexto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(LogoutBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BienvenidaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        CalificacionesBoton.setBackground(new java.awt.Color(204, 204, 204));
        CalificacionesBoton.setForeground(new java.awt.Color(0, 0, 0));
        CalificacionesBoton.setText("Calificaciones");
        CalificacionesBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CalificacionesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalificacionesBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalificacionesBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(ActividadesBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AulasBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(AulasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActividadesBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalificacionesBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void AulasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AulasBotonActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVentana("selAul");
    }//GEN-LAST:event_AulasBotonActionPerformed

    private void CalificacionesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalificacionesBotonActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVentana("calPan");
    }//GEN-LAST:event_CalificacionesBotonActionPerformed

    private void ActividadesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActividadesBotonActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVentana("actPan");
    }//GEN-LAST:event_ActividadesBotonActionPerformed

    private void LogoutBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBotonActionPerformed
        // TODO add your handling code here:
        controlador.logout();
    }//GEN-LAST:event_LogoutBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActividadesBoton;
    private javax.swing.JButton AulasBoton;
    private javax.swing.JLabel BienvenidaTexto;
    private javax.swing.JButton CalificacionesBoton;
    private javax.swing.JButton LogoutBoton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
