/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Estudiante;

import Controller.Controlador;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author Luis
 */
public class DashboardEstudiantePanel extends javax.swing.JPanel {

    private Controlador controlador;
    /**
     * Creates new form DashboardEstudiantePanel
     */
    public DashboardEstudiantePanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                // This code will execute when the JPanel becomes visible
                BienvenidaTexto.setText("¡Bienvenido, " + controlador.getEstudianteLogueado().getNombre_completo() + "!");

                // Perform actions here that should happen when the panel is displayed
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipalBoton = new javax.swing.JButton();
        VolverBoton = new javax.swing.JButton();
        CalificacionesBoton = new javax.swing.JButton();
        ActBoton = new javax.swing.JButton();
        AulasBoton = new javax.swing.JButton();
        BienvenidaTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPrincipalBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver (2).png"))); // NOI18N
        MenuPrincipalBoton.setBorderPainted(false);
        MenuPrincipalBoton.setContentAreaFilled(false);
        MenuPrincipalBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver (2)_hover.png"))); // NOI18N
        MenuPrincipalBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalBotonActionPerformed(evt);
            }
        });
        add(MenuPrincipalBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 70));

        VolverBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        VolverBoton.setBorderPainted(false);
        VolverBoton.setContentAreaFilled(false);
        VolverBoton.setFocusPainted(false);
        VolverBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        add(VolverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 70));

        CalificacionesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton CALIFICACIONES.png"))); // NOI18N
        CalificacionesBoton.setBorderPainted(false);
        CalificacionesBoton.setContentAreaFilled(false);
        CalificacionesBoton.setFocusPainted(false);
        CalificacionesBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton CALIFICACIONES_hover.png"))); // NOI18N
        CalificacionesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalificacionesBotonActionPerformed(evt);
            }
        });
        add(CalificacionesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 80));

        ActBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton ACTIVIDADES.png"))); // NOI18N
        ActBoton.setBorder(null);
        ActBoton.setBorderPainted(false);
        ActBoton.setContentAreaFilled(false);
        ActBoton.setFocusPainted(false);
        ActBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton ACTIVIDADES_hover.png"))); // NOI18N
        ActBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActBotonActionPerformed(evt);
            }
        });
        add(ActBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 80));

        AulasBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton AULAS.png"))); // NOI18N
        AulasBoton.setBorder(null);
        AulasBoton.setBorderPainted(false);
        AulasBoton.setContentAreaFilled(false);
        AulasBoton.setFocusPainted(false);
        AulasBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton AULAS_hover.png"))); // NOI18N
        AulasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AulasBotonActionPerformed(evt);
            }
        });
        add(AulasBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 260, 80));

        BienvenidaTexto.setFont(new java.awt.Font("Myanmar Text", 1, 48)); // NOI18N
        BienvenidaTexto.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidaTexto.setText("¡Bienvenido, Estudiante!");
        add(BienvenidaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 640, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Estudiante/img/9.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void CalificacionesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalificacionesBotonActionPerformed
        controlador.cambiarVentana("calPan");
    }//GEN-LAST:event_CalificacionesBotonActionPerformed

    private void AulasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AulasBotonActionPerformed
        controlador.cambiarVentana("selAul");
    }//GEN-LAST:event_AulasBotonActionPerformed

    private void ActBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActBotonActionPerformed
        controlador.cambiarVentana("actPan");
    }//GEN-LAST:event_ActBotonActionPerformed

    private void MenuPrincipalBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalBotonActionPerformed
        controlador.volverInicio();
    }//GEN-LAST:event_MenuPrincipalBotonActionPerformed

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        // TODO add your handling code here:
        controlador.logout();
    }//GEN-LAST:event_VolverBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActBoton;
    private javax.swing.JButton AulasBoton;
    private javax.swing.JLabel BienvenidaTexto;
    private javax.swing.JButton CalificacionesBoton;
    private javax.swing.JButton MenuPrincipalBoton;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
