/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Estudiante;

import Controller.Controlador;


public class UnirseAulaPanel extends javax.swing.JPanel {

    private Controlador controlador;
    
    public UnirseAulaPanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        VolverBoton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jButton1.setText("VERIFICAR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 150, 50));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 60)); // NOI18N
        jLabel3.setText("UNIRSE A AULA");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 490, 70));

        VolverBoton1.setFont(VolverBoton1.getFont());
        VolverBoton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Boton volver.png"))); // NOI18N
        VolverBoton1.setBorder(null);
        VolverBoton1.setBorderPainted(false);
        VolverBoton1.setContentAreaFilled(false);
        VolverBoton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Boton volver_hover.png"))); // NOI18N
        VolverBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBoton1ActionPerformed(evt);
            }
        });
        add(VolverBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 91, 70));

        jTextField1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 370, 90));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel2.setText("Ingrese el codigo de Invitacion de Aula");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 680, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Estudiante/img/12.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBoton1ActionPerformed
        controlador.volverPanelAnterior();
    }//GEN-LAST:event_VolverBoton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverBoton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
