/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;

import coil.prototipo.logica.Aula;
import coil.prototipo.logica.Docente;
import database.dbConnections;
import java.util.ArrayList;
import Controller.Controlador;
/**
 * Panel que muestra información detallada de un Aula para el docente.
 */
public class AulaInfoPanelDocente extends javax.swing.JPanel {

    private Controlador controlador;
    private Aula currentAula;

    public AulaInfoPanelDocente(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDocente = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        EditarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        VolverBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        jLabel1.setText("Informacion Aula");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 36));

        jLabelNombre.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabelNombre.setText("Nombre");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 101, 362, 40));

        jLabelDocente.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabelDocente.setText("Descripcion");
        add(jLabelDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 362, 40));

        jLabelCodigo.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabelCodigo.setText("Codigo");
        add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 362, 40));

        jLabelDesc.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabelDesc.setText("Docente");
        add(jLabelDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 362, 40));

        EditarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton EDITAR.png"))); // NOI18N
        EditarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EditarBoton.setBorderPainted(false);
        EditarBoton.setContentAreaFilled(false);
        EditarBoton.setFocusPainted(false);
        EditarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton EDITAR_hover.png"))); // NOI18N
        EditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBotonActionPerformed(evt);
            }
        });
        add(EditarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 280, 110));

        EliminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton ELIMINAR.png"))); // NOI18N
        EliminarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EliminarBoton.setBorderPainted(false);
        EliminarBoton.setContentAreaFilled(false);
        EliminarBoton.setFocusPainted(false);
        EliminarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton ELIMINAR_hover.png"))); // NOI18N
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });
        add(EliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 260, 110));

        VolverBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        VolverBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        VolverBoton.setBorderPainted(false);
        VolverBoton.setContentAreaFilled(false);
        VolverBoton.setFocusPainted(false);
        VolverBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        add(VolverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 90, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/14.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        controlador.volverPanelAnterior();
    }//GEN-LAST:event_VolverBotonActionPerformed

    private void EditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBotonActionPerformed
        if (currentAula == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay aula seleccionada.");
            return;
        }

        javax.swing.JTextField nombreField = new javax.swing.JTextField(currentAula.getNombre() != null ? currentAula.getNombre() : "");
        javax.swing.JTextArea descArea = new javax.swing.JTextArea(currentAula.getDescripcion() != null ? currentAula.getDescripcion() : "", 6, 30);
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(descArea);
        Object[] inputs = {"Nombre:", nombreField, "Descripción:", scroll};

        int res = javax.swing.JOptionPane.showConfirmDialog(this, inputs, "Editar Aula", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (res == javax.swing.JOptionPane.OK_OPTION) {
            String nuevoNombre = nombreField.getText().trim();
            String nuevaDesc = descArea.getText().trim();
            if (nuevoNombre.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
                return;
            }
            boolean ok = controlador.editarAula(String.valueOf(currentAula.getId_aula()), nuevoNombre, nuevaDesc);
            if (ok) {
                currentAula.setNombre(nuevoNombre);
                currentAula.setDescripcion(nuevaDesc);
                setAula(currentAula);
                javax.swing.JOptionPane.showMessageDialog(this, "Aula actualizada correctamente.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar el aula. Revisa logs.");
            }
        }
    }//GEN-LAST:event_EditarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        if (currentAula == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay aula seleccionada.");
            return;
        }
        int confirmado = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Confirma eliminar el aula \"" + (currentAula.getNombre() != null ? currentAula.getNombre() : currentAula.getId_aula()) + "\" ?",
                "Eliminar Aula", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirmado == javax.swing.JOptionPane.YES_OPTION) {
            boolean ok = controlador.eliminarAula(String.valueOf(currentAula.getId_aula()));
            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Aula eliminada.");
                setAula(null);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el aula. Revisa logs.");
            }
        }
    }//GEN-LAST:event_EliminarBotonActionPerformed

    
    public void setAula(Aula aula) {
        this.currentAula = aula;
        if (aula == null) {
            jLabelNombre.setText("Nombre: -");
            jLabelCodigo.setText("Código inscripción: -");
            jLabelDocente.setText("Docente: -");
            jLabelDesc.setText("Descripción: -");
            return;
        }
        jLabelNombre.setText("Nombre: " + (aula.getNombre() != null ? aula.getNombre() : "-"));
        jLabelCodigo.setText("Código inscripción: " + (aula.getCodigo_inscripcion() != null ? aula.getCodigo_inscripcion() : "-"));
        jLabelDesc.setText("Descripción: " + (aula.getDescripcion() != null ? aula.getDescripcion() : "-"));
        if (aula.getDocente() != null) {
            Docente d = aula.getDocente();
            jLabelDocente.setText("Docente: " + (d.getNombre_completo() != null ? d.getNombre_completo() : d.getCodigoDocente()));
        } else {
            jLabelDocente.setText("Docente: -");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarBoton;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelDocente;
    private javax.swing.JLabel jLabelNombre;
    // End of variables declaration//GEN-END:variables
}
