/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;
import Controller.Controlador;
import coil.prototipo.logica.Nota;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
/**
 *
 * @author luisr
 */
public class CalificacionesPanelDocente extends javax.swing.JPanel {

    private Controlador controlador;
    /**
     * Creates new form CalificacionesPanel
     */
    public CalificacionesPanelDocente(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        
        // truquito para correr codigo cuando se muestra el panel
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                controlador.llenarTablaNotasDoc(TablaNotas);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaNotas = new javax.swing.JTable();
        TextoNotas = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonExportar.setFont(BotonExportar.getFont());
        BotonExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton Exportar.png"))); // NOI18N
        BotonExportar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonExportar.setBorderPainted(false);
        BotonExportar.setContentAreaFilled(false);
        BotonExportar.setFocusPainted(false);
        BotonExportar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton Exportar Hover.png"))); // NOI18N
        BotonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExportarActionPerformed(evt);
            }
        });
        add(BotonExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 270, 50));

        TablaNotas.setBackground(new java.awt.Color(153, 255, 153));
        TablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaNotas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, 296));

        TextoNotas.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        TextoNotas.setText("CALIFICACIONES");
        add(TextoNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 60));

        BotonVolver.setFont(BotonVolver.getFont());
        BotonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Estudiante/img/Boton volver.png"))); // NOI18N
        BotonVolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonVolver.setBorderPainted(false);
        BotonVolver.setContentAreaFilled(false);
        BotonVolver.setFocusPainted(false);
        BotonVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Estudiante/img/Boton volver_hover.png"))); // NOI18N
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 120, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Estudiante/img/12.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonExportarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        controlador.volverPanelAnterior();

    }//GEN-LAST:event_BotonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonExportar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTable TablaNotas;
    private javax.swing.JLabel TextoNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
