/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;

import Controller.Controlador;
import javax.swing.JOptionPane;

public class CrearEjercicio extends javax.swing.JPanel {

    private Controlador controlador;
    
    public CrearEjercicio(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EnunciadoField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Opcion4Field = new javax.swing.JTextField();
        Opcion3Field = new javax.swing.JTextField();
        Opcion2Field = new javax.swing.JTextField();
        Opcion1Field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        CrearBoton = new javax.swing.JToggleButton();
        CancelarBoton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 25)); // NOI18N
        jLabel3.setText("OPCION N°4");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 150, 50));

        jScrollPane1.setBorder(null);

        EnunciadoField.setBackground(new java.awt.Color(102, 255, 204));
        EnunciadoField.setColumns(20);
        EnunciadoField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        EnunciadoField.setRows(5);
        jScrollPane1.setViewportView(EnunciadoField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 430, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 60)); // NOI18N
        jLabel1.setText("CREAR EJERCICIO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 90));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel4.setText("Enunciado del Ejercicio:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 360, 50));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel5.setText("Opciones de respuesta:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 350, 50));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 25)); // NOI18N
        jLabel6.setText("RES. CORRECTA: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, 50));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 25)); // NOI18N
        jLabel7.setText("OPCION N°2");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 150, 50));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 25)); // NOI18N
        jLabel8.setText("OPCION N°3");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 150, 50));

        Opcion4Field.setBackground(new java.awt.Color(102, 255, 204));
        Opcion4Field.setBorder(null);
        Opcion4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion4FieldActionPerformed(evt);
            }
        });
        add(Opcion4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 130, 50));

        Opcion3Field.setBackground(new java.awt.Color(102, 255, 204));
        Opcion3Field.setBorder(null);
        Opcion3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion3FieldActionPerformed(evt);
            }
        });
        add(Opcion3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 130, 50));

        Opcion2Field.setBackground(new java.awt.Color(102, 255, 204));
        Opcion2Field.setBorder(null);
        Opcion2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion2FieldActionPerformed(evt);
            }
        });
        add(Opcion2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 130, 50));

        Opcion1Field.setBackground(new java.awt.Color(102, 255, 204));
        Opcion1Field.setBorder(null);
        Opcion1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion1FieldActionPerformed(evt);
            }
        });
        add(Opcion1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 130, 50));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 25)); // NOI18N
        jLabel9.setText("OPCION N°1");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 150, 50));

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opcion 1", "Opcion 2", "Opcion 3", "Opcion 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 170, 40));

        CrearBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Crear Ejercicio Boton.png"))); // NOI18N
        CrearBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CrearBoton.setBorderPainted(false);
        CrearBoton.setContentAreaFilled(false);
        CrearBoton.setFocusPainted(false);
        CrearBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Crear Ejercicio Boton Hover.png"))); // NOI18N
        CrearBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBotonActionPerformed(evt);
            }
        });
        add(CrearBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 270, 60));

        CancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        CancelarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CancelarBoton.setBorderPainted(false);
        CancelarBoton.setContentAreaFilled(false);
        CancelarBoton.setFocusPainted(false);
        CancelarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });
        add(CancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 90, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/13.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void Opcion1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion1FieldActionPerformed

    private void Opcion2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion2FieldActionPerformed

    private void Opcion3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion3FieldActionPerformed

    private void Opcion4FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion4FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion4FieldActionPerformed

    private void CrearBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBotonActionPerformed
        if (EnunciadoField.getText().isEmpty() || Opcion1Field.getText().isEmpty() || Opcion2Field.getText().isEmpty() || Opcion3Field.getText().isEmpty() || Opcion4Field.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos de texto deben de estar llenos.", "Campos de texto vacíos", JOptionPane.ERROR_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, "Ejercicio creado exitosamente.", "Creación exitosa del ejercicio", JOptionPane.INFORMATION_MESSAGE);
            controlador.volverPanelAnterior();

        }
    }//GEN-LAST:event_CrearBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        controlador.volverPanelAnterior();
    }//GEN-LAST:event_CancelarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CancelarBoton;
    private javax.swing.JToggleButton CrearBoton;
    private javax.swing.JTextArea EnunciadoField;
    private javax.swing.JTextField Opcion1Field;
    private javax.swing.JTextField Opcion2Field;
    private javax.swing.JTextField Opcion3Field;
    private javax.swing.JTextField Opcion4Field;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
