/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;

import Controller.Controlador;

/**
 *
 * @author luisr
 */
public class CrearActividadPanel extends javax.swing.JPanel {
    private Controlador controlador;
    /**
     * Creates new form CrearActividadPanel
     */
    public CrearActividadPanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TemasComboBox = new javax.swing.JComboBox<>();
        NombreField = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        TemaLabel = new javax.swing.JLabel();
        DescripcionField = new javax.swing.JTextField();
        DescripcionLabel = new javax.swing.JLabel();
        CancelarBoton = new javax.swing.JButton();
        ElegirEjerciciosBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TemasComboBox.setBackground(new java.awt.Color(255, 153, 0));
        TemasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TemasComboBox.setBorder(null);
        TemasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemasComboBoxActionPerformed(evt);
            }
        });
        add(TemasComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 309, 29));

        NombreField.setBackground(new java.awt.Color(255, 153, 0));
        NombreField.setBorder(null);
        NombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFieldActionPerformed(evt);
            }
        });
        add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 400, 29));

        NombreLabel.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        NombreLabel.setText("Nombre");
        add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 130, -1));

        TemaLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        TemaLabel.setText("Tema");
        add(TemaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        DescripcionField.setBackground(new java.awt.Color(255, 153, 0));
        DescripcionField.setBorder(null);
        DescripcionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionFieldActionPerformed(evt);
            }
        });
        add(DescripcionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 540, 97));

        DescripcionLabel.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        DescripcionLabel.setText("Descripcion");
        add(DescripcionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        CancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        CancelarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CancelarBoton.setBorderPainted(false);
        CancelarBoton.setContentAreaFilled(false);
        CancelarBoton.setFocusPainted(false);
        CancelarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });
        add(CancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 100, 70));

        ElegirEjerciciosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton ELEGIR EJERCICIOS.png"))); // NOI18N
        ElegirEjerciciosBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ElegirEjerciciosBoton.setBorderPainted(false);
        ElegirEjerciciosBoton.setContentAreaFilled(false);
        ElegirEjerciciosBoton.setFocusPainted(false);
        ElegirEjerciciosBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton ELEGIR EJERCICIOS_hover.png"))); // NOI18N
        ElegirEjerciciosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirEjerciciosBotonActionPerformed(evt);
            }
        });
        add(ElegirEjerciciosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/16.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void NombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFieldActionPerformed

    private void DescripcionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionFieldActionPerformed

    private void TemasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemasComboBoxActionPerformed
        // TODO add your handling code here:
        controlador.LlenarCBTemas(TemasComboBox);
    }//GEN-LAST:event_TemasComboBoxActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        controlador.volverPanelAnterior();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void ElegirEjerciciosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirEjerciciosBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElegirEjerciciosBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JTextField DescripcionField;
    private javax.swing.JLabel DescripcionLabel;
    private javax.swing.JButton ElegirEjerciciosBoton;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JLabel TemaLabel;
    private javax.swing.JComboBox<String> TemasComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
