/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;

import Controller.Controlador;
import javax.swing.JOptionPane;

/**
 * Panel para que el docente cree una nueva aula (nombre + descripción).
 */
public class CrearAulaPanelDocente extends javax.swing.JPanel {

    private final Controlador controlador;

    /**
     * Creates new form CrearAulaPanelDocente
     */
    public CrearAulaPanelDocente(Controlador controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        CrearBoton = new javax.swing.JToggleButton();
        CancelarBoton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        jLabel1.setText("CREAR AULA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 37));

        txtNombre.setBackground(new java.awt.Color(255, 51, 51));
        txtNombre.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtNombre.setBorder(null);
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 390, 50));

        txtDescripcion.setBackground(new java.awt.Color(255, 51, 51));
        txtDescripcion.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtDescripcion.setBorder(null);
        add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 390, 160));

        CrearBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton CREAR AULA.png"))); // NOI18N
        CrearBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CrearBoton.setBorderPainted(false);
        CrearBoton.setContentAreaFilled(false);
        CrearBoton.setFocusPainted(false);
        CrearBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton CREAR AULA_hover.png"))); // NOI18N
        CrearBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBotonActionPerformed(evt);
            }
        });
        add(CrearBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 270, 110));

        CancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        CancelarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CancelarBoton.setBorderPainted(false);
        CancelarBoton.setContentAreaFilled(false);
        CancelarBoton.setFocusPainted(false);
        CancelarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });
        add(CancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 90, 70));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel3.setText("Descripcion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/14.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CrearBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBotonActionPerformed
        String nombre = txtNombre.getText().trim();
        String descripcion = txtDescripcion.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del aula es obligatorio.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean ok = controlador.crearAula(nombre, descripcion);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Aula creada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.setText("");
            txtDescripcion.setText("");
            // Volver al panel de aulas
            controlador.cambiarVentana("aulDoc");
        } // else el controlador ya mostró un error
    }//GEN-LAST:event_CrearBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        controlador.cambiarVentana("aulDoc");
    }//GEN-LAST:event_CancelarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CancelarBoton;
    private javax.swing.JToggleButton CrearBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
