/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;

import Controller.Controlador;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author Luis
 */
public class DashboardDocentePanel extends javax.swing.JPanel {
    private Controlador controlador;
    /**
     * Creates new form DashboardDocentePanel
     */
    public DashboardDocentePanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
         this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                // This code will execute when the JPanel becomes visible
                BienvenidaTexto.setText("¡Bienvenido, " + controlador.getDocenteLogueado().getNombre_completo() + "!");

                // Perform actions here that should happen when the panel is displayed
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EjerciciosBoton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        LogoutBoton = new javax.swing.JButton();
        CalificacionesBoton = new javax.swing.JButton();
        ActividadesBoton = new javax.swing.JButton();
        AulasBoton = new javax.swing.JButton();
        BienvenidaTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EjerciciosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Estudiante/img/Boton EJERCICIOS.png"))); // NOI18N
        EjerciciosBoton.setBorderPainted(false);
        EjerciciosBoton.setContentAreaFilled(false);
        EjerciciosBoton.setFocusPainted(false);
        EjerciciosBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Estudiante/img/Boton EJERCICIOS_hover.png"))); // NOI18N
        EjerciciosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjerciciosBotonActionPerformed(evt);
            }
        });
        add(EjerciciosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 270, 100));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver (2).png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver (2)_hover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 70));

        LogoutBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver.png"))); // NOI18N
        LogoutBoton.setBorderPainted(false);
        LogoutBoton.setContentAreaFilled(false);
        LogoutBoton.setFocusPainted(false);
        LogoutBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton volver_hover.png"))); // NOI18N
        LogoutBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBotonActionPerformed(evt);
            }
        });
        add(LogoutBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 70));

        CalificacionesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton CALIFICACIONES.png"))); // NOI18N
        CalificacionesBoton.setBorderPainted(false);
        CalificacionesBoton.setContentAreaFilled(false);
        CalificacionesBoton.setFocusPainted(false);
        CalificacionesBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton CALIFICACIONES_hover.png"))); // NOI18N
        CalificacionesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalificacionesBotonActionPerformed(evt);
            }
        });
        add(CalificacionesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 100));

        ActividadesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton ACTIVIDADES.png"))); // NOI18N
        ActividadesBoton.setBorder(null);
        ActividadesBoton.setBorderPainted(false);
        ActividadesBoton.setContentAreaFilled(false);
        ActividadesBoton.setFocusPainted(false);
        ActividadesBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton ACTIVIDADES_hover.png"))); // NOI18N
        ActividadesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActividadesBotonActionPerformed(evt);
            }
        });
        add(ActividadesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, 100));

        AulasBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton AULAS.png"))); // NOI18N
        AulasBoton.setBorder(null);
        AulasBoton.setBorderPainted(false);
        AulasBoton.setContentAreaFilled(false);
        AulasBoton.setFocusPainted(false);
        AulasBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/Boton AULAS_hover.png"))); // NOI18N
        AulasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AulasBotonActionPerformed(evt);
            }
        });
        add(AulasBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 260, 100));

        BienvenidaTexto.setFont(new java.awt.Font("Myanmar Text", 1, 48)); // NOI18N
        BienvenidaTexto.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidaTexto.setText("¡Bienvenido, Docente!");
        add(BienvenidaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 560, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/img/10.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void AulasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AulasBotonActionPerformed
        // TODO add your handling code here:
                controlador.cambiarVentana("aulDoc");

    }//GEN-LAST:event_AulasBotonActionPerformed

    private void CalificacionesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalificacionesBotonActionPerformed
        // TODO add your handling code here:
                controlador.cambiarVentana("repDoc");

    }//GEN-LAST:event_CalificacionesBotonActionPerformed

    private void ActividadesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActividadesBotonActionPerformed
        // TODO add your handling code here:
                controlador.cambiarVentana("actDoc");

    }//GEN-LAST:event_ActividadesBotonActionPerformed

    private void EjerciciosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjerciciosBotonActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVentana("verEjer");
    }//GEN-LAST:event_EjerciciosBotonActionPerformed

    private void LogoutBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBotonActionPerformed
        // TODO add your handling code here:
        controlador.logout();
    }//GEN-LAST:event_LogoutBotonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        controlador.volverInicio();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActividadesBoton;
    private javax.swing.JButton AulasBoton;
    private javax.swing.JLabel BienvenidaTexto;
    private javax.swing.JButton CalificacionesBoton;
    private javax.swing.JButton EjerciciosBoton;
    private javax.swing.JButton LogoutBoton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
