/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;

import Controller.Controlador;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author luisr
 */
public class ElegirEjerciciosActPanel extends javax.swing.JPanel {
    private Controlador controlador;
    /**
     * Creates new form CrearActividadPanel
     */
    public ElegirEjerciciosActPanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                controlador.agregarChecklistPreguntas(ContenedorChecklist);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelarBoton = new javax.swing.JButton();
        ElegirEjerciciosBoton = new javax.swing.JButton();
        ContenedorChecklist = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton volver.png"))); // NOI18N
        CancelarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CancelarBoton.setBorderPainted(false);
        CancelarBoton.setContentAreaFilled(false);
        CancelarBoton.setFocusPainted(false);
        CancelarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton volver_hover.png"))); // NOI18N
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });
        add(CancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 100, 70));

        ElegirEjerciciosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Crear Actividad Boton.png"))); // NOI18N
        ElegirEjerciciosBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ElegirEjerciciosBoton.setBorderPainted(false);
        ElegirEjerciciosBoton.setContentAreaFilled(false);
        ElegirEjerciciosBoton.setFocusPainted(false);
        ElegirEjerciciosBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Crear Actividad Hover.png"))); // NOI18N
        add(ElegirEjerciciosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 280, 140));
        add(ContenedorChecklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 590, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/16.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        controlador.volverPanelAnterior();
    }//GEN-LAST:event_CancelarBotonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JPanel ContenedorChecklist;
    private javax.swing.JButton ElegirEjerciciosBoton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
