/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Docente;

import Controller.Controlador;
import java.awt.Font;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane;

public class VerEjerciciosPanel extends javax.swing.JPanel {
    
    private Font customFont;
    private Controlador controlador;
    
    public VerEjerciciosPanel(Controlador controlador) {
        initComponents();
        this.controlador = controlador;        
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                controlador.llenarListaActividades(EjercicioLista);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        EjercicioLista = new javax.swing.JList<>();
        CrearEjercicioBoton = new javax.swing.JButton();
        VolverBoton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);

        EjercicioLista.setBackground(new java.awt.Color(102, 255, 204));
        EjercicioLista.setBorder(null);
        EjercicioLista.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        EjercicioLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(EjercicioLista);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 500, 290));

        CrearEjercicioBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton ELEGIR EJERCICIOS (3).png"))); // NOI18N
        CrearEjercicioBoton.setBorderPainted(false);
        CrearEjercicioBoton.setContentAreaFilled(false);
        CrearEjercicioBoton.setFocusPainted(false);
        CrearEjercicioBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/Boton ELEGIR EJERCICIOS (3)_hover.png"))); // NOI18N
        CrearEjercicioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEjercicioBotonActionPerformed(evt);
            }
        });
        add(CrearEjercicioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 260, -1));

        VolverBoton1.setFont(VolverBoton1.getFont());
        VolverBoton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Boton volver.png"))); // NOI18N
        VolverBoton1.setBorder(null);
        VolverBoton1.setBorderPainted(false);
        VolverBoton1.setContentAreaFilled(false);
        VolverBoton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Boton volver_hover.png"))); // NOI18N
        VolverBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBoton1ActionPerformed(evt);
            }
        });
        add(VolverBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 91, 70));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 60)); // NOI18N
        jLabel1.setText("EJERCICIOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Docente/13.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBoton1ActionPerformed
        controlador.volverPanelDashboard();
    }//GEN-LAST:event_VolverBoton1ActionPerformed

    private void CrearEjercicioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEjercicioBotonActionPerformed
        controlador.cambiarVentana("crearEj");
    }//GEN-LAST:event_CrearEjercicioBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearEjercicioBoton;
    private javax.swing.JList<String> EjercicioLista;
    private javax.swing.JButton VolverBoton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
